import { Student, FeeStatus } from '../types';

export const INITIAL_STUDENTS: Student[] = [
  {
    id: '1',
    name: 'Alice Johnson',
    regNo: 'CS2023001',
    email: 'alice.j@uni.edu',
    department: 'Computer Science',
    year: 3,
    semester: 5,
    avatarUrl: 'https://picsum.photos/200/200?random=1',
    contact: '+1 555-0101',
    address: '123 Campus Way, Tech City',
    attendancePercentage: 85,
    totalClasses: 120,
    attendedClasses: 102,
    feeStatus: FeeStatus.PAID,
    totalFee: 5000,
    paidFee: 5000,
    pendingFee: 0,
    cgpa: 3.8,
    results: [
      { code: 'CS301', name: 'Data Structures', marks: 88, maxMarks: 100, grade: 'A', status: 'PASS' },
      { code: 'CS302', name: 'Algorithms', marks: 75, maxMarks: 100, grade: 'B', status: 'PASS' },
      { code: 'CS303', name: 'Database Systems', marks: 92, maxMarks: 100, grade: 'A+', status: 'PASS' },
      { code: 'MA301', name: 'Linear Algebra', marks: 65, maxMarks: 100, grade: 'C', status: 'PASS' },
    ]
  },
  {
    id: '2',
    name: 'Bob Smith',
    regNo: 'ME2023045',
    email: 'bob.s@uni.edu',
    department: 'Mechanical Engineering',
    year: 2,
    semester: 3,
    avatarUrl: 'https://picsum.photos/200/200?random=2',
    contact: '+1 555-0102',
    address: '456 Gear Avenue, Mech Town',
    attendancePercentage: 62,
    totalClasses: 100,
    attendedClasses: 62,
    feeStatus: FeeStatus.PENDING,
    totalFee: 5000,
    paidFee: 2000,
    pendingFee: 3000,
    cgpa: 3.2,
    results: [
      { code: 'ME201', name: 'Thermodynamics', marks: 55, maxMarks: 100, grade: 'D', status: 'PASS' },
      { code: 'ME202', name: 'Fluid Mechanics', marks: 42, maxMarks: 100, grade: 'F', status: 'FAIL' },
      { code: 'MA201', name: 'Calculus III', marks: 70, maxMarks: 100, grade: 'B', status: 'PASS' },
    ]
  },
  {
    id: '3',
    name: 'Charlie Davis',
    regNo: 'EE2023012',
    email: 'charlie.d@uni.edu',
    department: 'Electrical Engineering',
    year: 4,
    semester: 7,
    avatarUrl: 'https://picsum.photos/200/200?random=3',
    contact: '+1 555-0103',
    address: '789 Circuit Blvd, Electro City',
    attendancePercentage: 95,
    totalClasses: 140,
    attendedClasses: 133,
    feeStatus: FeeStatus.PAID,
    totalFee: 5500,
    paidFee: 5500,
    pendingFee: 0,
    cgpa: 3.9,
    results: [
      { code: 'EE401', name: 'Control Systems', marks: 95, maxMarks: 100, grade: 'O', status: 'PASS' },
      { code: 'EE402', name: 'Power Electronics', marks: 89, maxMarks: 100, grade: 'A', status: 'PASS' },
    ]
  },
  {
    id: '4',
    name: 'Diana Prince',
    regNo: 'AR2023099',
    email: 'diana.p@uni.edu',
    department: 'Architecture',
    year: 1,
    semester: 1,
    avatarUrl: 'https://picsum.photos/200/200?random=4',
    contact: '+1 555-0104',
    address: '321 Design Lane, Art City',
    attendancePercentage: 78,
    totalClasses: 80,
    attendedClasses: 62,
    feeStatus: FeeStatus.OVERDUE,
    totalFee: 6000,
    paidFee: 0,
    pendingFee: 6000,
    cgpa: 3.5,
    results: [
      { code: 'AR101', name: 'History of Architecture', marks: 80, maxMarks: 100, grade: 'A', status: 'PASS' },
      { code: 'AR102', name: 'Design Studio I', marks: 78, maxMarks: 100, grade: 'B+', status: 'PASS' },
    ]
  },
  {
    id: '5',
    name: 'Evan Wright',
    regNo: 'CV2023055',
    email: 'evan.w@uni.edu',
    department: 'Civil Engineering',
    year: 3,
    semester: 6,
    avatarUrl: 'https://picsum.photos/200/200?random=5',
    contact: '+1 555-0105',
    address: '890 Concrete Rd, Build Town',
    attendancePercentage: 91,
    totalClasses: 130,
    attendedClasses: 118,
    feeStatus: FeeStatus.PAID,
    totalFee: 5200,
    paidFee: 5200,
    pendingFee: 0,
    cgpa: 3.6,
    results: [
      { code: 'CV301', name: 'Structural Analysis', marks: 82, maxMarks: 100, grade: 'A', status: 'PASS' },
      { code: 'CV302', name: 'Geotechnical Eng', marks: 78, maxMarks: 100, grade: 'B+', status: 'PASS' },
    ]
  },
  {
    id: '6',
    name: 'Fiona Gallagher',
    regNo: 'BT2023022',
    email: 'fiona.g@uni.edu',
    department: 'Biotechnology',
    year: 2,
    semester: 4,
    avatarUrl: 'https://picsum.photos/200/200?random=6',
    contact: '+1 555-0106',
    address: '567 Gene Street, Lab City',
    attendancePercentage: 88,
    totalClasses: 110,
    attendedClasses: 97,
    feeStatus: FeeStatus.PENDING,
    totalFee: 5800,
    paidFee: 2900,
    pendingFee: 2900,
    cgpa: 3.75,
    results: [
      { code: 'BT201', name: 'Microbiology', marks: 90, maxMarks: 100, grade: 'A+', status: 'PASS' },
      { code: 'BT202', name: 'Genetics', marks: 85, maxMarks: 100, grade: 'A', status: 'PASS' },
    ]
  },
  {
    id: '7',
    name: 'George Miller',
    regNo: 'IT2023088',
    email: 'george.m@uni.edu',
    department: 'Information Technology',
    year: 4,
    semester: 8,
    avatarUrl: 'https://picsum.photos/200/200?random=7',
    contact: '+1 555-0107',
    address: '404 Web Way, Cyber City',
    attendancePercentage: 45,
    totalClasses: 60,
    attendedClasses: 27,
    feeStatus: FeeStatus.OVERDUE,
    totalFee: 5500,
    paidFee: 0,
    pendingFee: 5500,
    cgpa: 2.8,
    results: [
      { code: 'IT401', name: 'Cloud Computing', marks: 45, maxMarks: 100, grade: 'D', status: 'PASS' },
      { code: 'IT402', name: 'Network Security', marks: 35, maxMarks: 100, grade: 'F', status: 'FAIL' },
    ]
  },
  {
    id: '8',
    name: 'Hannah Lee',
    regNo: 'EC2023101',
    email: 'hannah.l@uni.edu',
    department: 'Electronics & Communication',
    year: 1,
    semester: 2,
    avatarUrl: 'https://picsum.photos/200/200?random=8',
    contact: '+1 555-0108',
    address: '77 Silicon Valley, Chip Town',
    attendancePercentage: 96,
    totalClasses: 90,
    attendedClasses: 86,
    feeStatus: FeeStatus.PAID,
    totalFee: 6000,
    paidFee: 6000,
    pendingFee: 0,
    cgpa: 4.0,
    results: [
      { code: 'EC101', name: 'Digital Electronics', marks: 98, maxMarks: 100, grade: 'O', status: 'PASS' },
      { code: 'EC102', name: 'Signals & Systems', marks: 92, maxMarks: 100, grade: 'A+', status: 'PASS' },
    ]
  },
  {
    id: '9',
    name: 'Ian Clark',
    regNo: 'CS2023150',
    email: 'ian.c@uni.edu',
    department: 'Computer Science',
    year: 2,
    semester: 4,
    avatarUrl: 'https://picsum.photos/200/200?random=9',
    contact: '+1 555-0109',
    address: '234 Code Lane, Dev City',
    attendancePercentage: 70,
    totalClasses: 110,
    attendedClasses: 77,
    feeStatus: FeeStatus.PAID,
    totalFee: 5000,
    paidFee: 5000,
    pendingFee: 0,
    cgpa: 3.1,
    results: [
      { code: 'CS201', name: 'OOP Java', marks: 65, maxMarks: 100, grade: 'C+', status: 'PASS' },
      { code: 'CS202', name: 'OS', marks: 58, maxMarks: 100, grade: 'C', status: 'PASS' },
    ]
  },
  {
    id: '10',
    name: 'Julia White',
    regNo: 'ME2023200',
    email: 'julia.w@uni.edu',
    department: 'Mechanical Engineering',
    year: 4,
    semester: 8,
    avatarUrl: 'https://picsum.photos/200/200?random=10',
    contact: '+1 555-0110',
    address: '101 Piston Ave, Auto City',
    attendancePercentage: 82,
    totalClasses: 60,
    attendedClasses: 49,
    feeStatus: FeeStatus.PAID,
    totalFee: 5000,
    paidFee: 5000,
    pendingFee: 0,
    cgpa: 3.65,
    results: [
      { code: 'ME401', name: 'Robotics', marks: 85, maxMarks: 100, grade: 'A', status: 'PASS' },
      { code: 'ME402', name: 'Project Work', marks: 90, maxMarks: 100, grade: 'A+', status: 'PASS' },
    ]
  },
  {
    id: '11',
    name: 'Kevin Hall',
    regNo: 'CV2023250',
    email: 'kevin.h@uni.edu',
    department: 'Civil Engineering',
    year: 1,
    semester: 1,
    avatarUrl: 'https://picsum.photos/200/200?random=11',
    contact: '+1 555-0111',
    address: '55 Bridge St, Construct City',
    attendancePercentage: 89,
    totalClasses: 80,
    attendedClasses: 71,
    feeStatus: FeeStatus.OVERDUE,
    totalFee: 5200,
    paidFee: 1000,
    pendingFee: 4200,
    cgpa: 3.4,
    results: [
      { code: 'CV101', name: 'Engg Mechanics', marks: 75, maxMarks: 100, grade: 'B+', status: 'PASS' },
      { code: 'MA101', name: 'Calculus I', marks: 80, maxMarks: 100, grade: 'A', status: 'PASS' },
    ]
  },
  {
    id: '12',
    name: 'Laura King',
    regNo: 'AR2023300',
    email: 'laura.k@uni.edu',
    department: 'Architecture',
    year: 3,
    semester: 5,
    avatarUrl: 'https://picsum.photos/200/200?random=12',
    contact: '+1 555-0112',
    address: '88 Arch Way, Design Hub',
    attendancePercentage: 92,
    totalClasses: 140,
    attendedClasses: 129,
    feeStatus: FeeStatus.PAID,
    totalFee: 6000,
    paidFee: 6000,
    pendingFee: 0,
    cgpa: 3.95,
    results: [
      { code: 'AR301', name: 'Urban Planning', marks: 94, maxMarks: 100, grade: 'O', status: 'PASS' },
      { code: 'AR302', name: 'Interior Design', marks: 88, maxMarks: 100, grade: 'A', status: 'PASS' },
    ]
  },
  {
    id: '13',
    name: 'Mike Scott',
    regNo: 'IT2023350',
    email: 'mike.s@uni.edu',
    department: 'Information Technology',
    year: 3,
    semester: 5,
    avatarUrl: 'https://picsum.photos/200/200?random=13',
    contact: '+1 555-0113',
    address: '42 Server Rd, Net Town',
    attendancePercentage: 60,
    totalClasses: 120,
    attendedClasses: 72,
    feeStatus: FeeStatus.PENDING,
    totalFee: 5500,
    paidFee: 3000,
    pendingFee: 2500,
    cgpa: 2.9,
    results: [
      { code: 'IT301', name: 'Web Dev', marks: 78, maxMarks: 100, grade: 'B+', status: 'PASS' },
      { code: 'IT302', name: 'Networking', marks: 45, maxMarks: 100, grade: 'D', status: 'PASS' },
    ]
  },
  {
    id: '14',
    name: 'Nora Green',
    regNo: 'BT2023400',
    email: 'nora.g@uni.edu',
    department: 'Biotechnology',
    year: 1,
    semester: 2,
    avatarUrl: 'https://picsum.photos/200/200?random=14',
    contact: '+1 555-0114',
    address: '12 Cell Block, Bio Park',
    attendancePercentage: 98,
    totalClasses: 90,
    attendedClasses: 88,
    feeStatus: FeeStatus.PAID,
    totalFee: 5800,
    paidFee: 5800,
    pendingFee: 0,
    cgpa: 3.8,
    results: [
      { code: 'BT101', name: 'Biochem I', marks: 85, maxMarks: 100, grade: 'A', status: 'PASS' },
      { code: 'BT102', name: 'Cell Biology', marks: 90, maxMarks: 100, grade: 'A+', status: 'PASS' },
    ]
  },
  {
    id: '15',
    name: 'Oliver Adams',
    regNo: 'EE2023450',
    email: 'oliver.a@uni.edu',
    department: 'Electrical Engineering',
    year: 2,
    semester: 3,
    avatarUrl: 'https://picsum.photos/200/200?random=15',
    contact: '+1 555-0115',
    address: '90 Voltage Dr, Amp City',
    attendancePercentage: 75,
    totalClasses: 100,
    attendedClasses: 75,
    feeStatus: FeeStatus.OVERDUE,
    totalFee: 5500,
    paidFee: 0,
    pendingFee: 5500,
    cgpa: 3.3,
    results: [
      { code: 'EE201', name: 'Circuits II', marks: 60, maxMarks: 100, grade: 'C', status: 'PASS' },
      { code: 'EE202', name: 'EM Fields', marks: 68, maxMarks: 100, grade: 'C+', status: 'PASS' },
    ]
  },
  {
    id: '16',
    name: 'Paul Baker',
    regNo: 'EC2023500',
    email: 'paul.b@uni.edu',
    department: 'Electronics & Communication',
    year: 3,
    semester: 6,
    avatarUrl: 'https://picsum.photos/200/200?random=16',
    contact: '+1 555-0116',
    address: '67 Radio Rd, Wave Town',
    attendancePercentage: 88,
    totalClasses: 130,
    attendedClasses: 114,
    feeStatus: FeeStatus.PAID,
    totalFee: 6000,
    paidFee: 6000,
    pendingFee: 0,
    cgpa: 3.7,
    results: [
      { code: 'EC301', name: 'VLSI Design', marks: 82, maxMarks: 100, grade: 'A', status: 'PASS' },
      { code: 'EC302', name: 'Comm Systems', marks: 79, maxMarks: 100, grade: 'B+', status: 'PASS' },
    ]
  },
  {
    id: '17',
    name: 'Quinn Young',
    regNo: 'CS2023550',
    email: 'quinn.y@uni.edu',
    department: 'Computer Science',
    year: 4,
    semester: 7,
    avatarUrl: 'https://picsum.photos/200/200?random=17',
    contact: '+1 555-0117',
    address: '555 Data Dr, Cloud City',
    attendancePercentage: 91,
    totalClasses: 80,
    attendedClasses: 73,
    feeStatus: FeeStatus.PENDING,
    totalFee: 5000,
    paidFee: 1000,
    pendingFee: 4000,
    cgpa: 3.5,
    results: [
      { code: 'CS401', name: 'AI & ML', marks: 88, maxMarks: 100, grade: 'A', status: 'PASS' },
      { code: 'CS402', name: 'Big Data', marks: 84, maxMarks: 100, grade: 'A', status: 'PASS' },
    ]
  },
  {
    id: '18',
    name: 'Rachel Hill',
    regNo: 'ME2023600',
    email: 'rachel.h@uni.edu',
    department: 'Mechanical Engineering',
    year: 1,
    semester: 2,
    avatarUrl: 'https://picsum.photos/200/200?random=18',
    contact: '+1 555-0118',
    address: '33 Gearbox Ln, Engine City',
    attendancePercentage: 94,
    totalClasses: 90,
    attendedClasses: 85,
    feeStatus: FeeStatus.PAID,
    totalFee: 5000,
    paidFee: 5000,
    pendingFee: 0,
    cgpa: 3.85,
    results: [
      { code: 'ME101', name: 'Engg Graphics', marks: 92, maxMarks: 100, grade: 'A+', status: 'PASS' },
      { code: 'MA102', name: 'Calculus II', marks: 88, maxMarks: 100, grade: 'A', status: 'PASS' },
    ]
  },
  {
    id: '19',
    name: 'Sam Turner',
    regNo: 'CV2023650',
    email: 'sam.t@uni.edu',
    department: 'Civil Engineering',
    year: 2,
    semester: 4,
    avatarUrl: 'https://picsum.photos/200/200?random=19',
    contact: '+1 555-0119',
    address: '12 Cement St, Build City',
    attendancePercentage: 65,
    totalClasses: 110,
    attendedClasses: 71,
    feeStatus: FeeStatus.PAID,
    totalFee: 5200,
    paidFee: 5200,
    pendingFee: 0,
    cgpa: 3.0,
    results: [
      { code: 'CV201', name: 'Surveying', marks: 55, maxMarks: 100, grade: 'D', status: 'PASS' },
      { code: 'CV202', name: 'Fluid Mech', marks: 60, maxMarks: 100, grade: 'C', status: 'PASS' },
    ]
  },
  {
    id: '20',
    name: 'Tina Phillips',
    regNo: 'AR2023700',
    email: 'tina.p@uni.edu',
    department: 'Architecture',
    year: 4,
    semester: 7,
    avatarUrl: 'https://picsum.photos/200/200?random=20',
    contact: '+1 555-0120',
    address: '99 Sketch Blvd, Draft Town',
    attendancePercentage: 80,
    totalClasses: 80,
    attendedClasses: 64,
    feeStatus: FeeStatus.PENDING,
    totalFee: 6000,
    paidFee: 2000,
    pendingFee: 4000,
    cgpa: 3.45,
    results: [
      { code: 'AR401', name: 'Sustainable Arch', marks: 82, maxMarks: 100, grade: 'A', status: 'PASS' },
      { code: 'AR402', name: 'Thesis Project', marks: 85, maxMarks: 100, grade: 'A', status: 'PASS' },
    ]
  }
];

// Helper to simulate API delay
export const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));
